import React from "react";
import "./Projects.css";
import gmeet from "../../assets/gmeet.png";
import drmenti from "../../assets/drmenti.png";
import sorting from "../../assets/sorting.png";
import { FaReact, FaHardHat } from "react-icons/fa";
import {
  SiBlockchaindotcom,
  SiHtml5,
  SiMaterialui,
  SiChai,
  SiEthereum,
  SiExpress,
  SiSocketdotio,
  SiTailwindcss,
  SiReactrouter,
  SiJavascript,
  SiMongodb,
  SiNodedotjs,
} from "react-icons/si";
import { DiCss3 } from "react-icons/di";
import { VscJson } from "react-icons/vsc";
import { IoLogoJavascript } from "react-icons/io";
export const Projects = () => {
  return (
    <>
      <div className="section">
        <h2 className="section__title different">Projects</h2>
        <div className="allProjects">
          <div className="projects_container" data-aos="fade-right">
            <div className="project">
              <div className="project_videocontainer">
                <div>
                  <img
                    src={drmenti}
                    alt="Group Meet App"
                  />
                </div>
              </div>
              <div className="project_information">
                <h2>Dr. Menti</h2>
                <p>
                  Dr. Menti is an web application to check on the user's mental health and it suggests videos to watch according to the result generated by the quiz.
                </p>
                <div>
                  <SiNodedotjs />
                  <SiExpress />
                  <DiCss3 />
                  <SiHtml5 />
                  <IoLogoJavascript />
                </div>
                <div>
                  <a
                    href="https://nikhilvip.github.io/Dr.Menti/"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <span type="button" className="btns onbt onbt">
                      See this Live
                    </span>
                  </a>
                  <a
                    href="https://github.com/nikhilVip/Dr.Menti"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <span type="button" className="btns onbt">
                      View Code
                    </span>
                  </a>
                </div>
              </div>
            </div>
          </div>
          <div className="projects_container" data-aos="fade-right">
            <div className="project">
              <div className="project_videocontainer">
                <div>
                  <img
                    src={gmeet}
                    alt="Group Meet App"
                  />
                </div>
              </div>
              <div className="project_information">
                <h2>Gmeet</h2>
                <p>
                Gmeet is a video calling web application which can be used to have one-on-one sessions and group calls using a single link.

                </p>
                <div>
                  <DiCss3 />
                  <SiHtml5 />
                  <IoLogoJavascript />
                </div>
                <div>
                  <a
                    href="https://nikhilvip.github.io/Gmeet-Group-Meet/index1.html"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <span type="button" className="btns onbt">
                      See this Live
                    </span>
                  </a>
                  <a
                    href="https://github.com/nikhilVip/Gmeet-Group-Meet"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <span type="button" className="btns onbt">
                      View Code
                    </span>
                  </a>
                </div>
              </div>
            </div>
          </div>
          

         
          <div className="projects_container" data-aos="fade-right">
            <div className="project">
              <div className="project_videocontainer">
                <div>
                  <img
                    src={sorting}
                    alt="Uniqlo-Clone"
                  />
                </div>
              </div>
              <div className="project_information">
                <h2>Sorting Visualizer</h2>
                <p>
                 This website is made to understand various sorting algorithms by using beautiful reperesentation for visualizations.
                </p>
                <div>
                  {/* <SiNodedotjs />
                  <SiExpress />
                  <SiMongodb /> */}
                  <SiHtml5 />
                  <DiCss3 />
                  <FaReact />
                </div>
                <div>
                  <a
                    href="https://nikhilvipsortingvisualizer.netlify.app/"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <span type="button" className="btns onbt onbt">
                      See this Live
                    </span>
                  </a>
                  <a
                    href="https://github.com/nikhilVip/SortingVisualizer"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <span type="button" className="btns onbt">
                      View Code
                    </span>
                  </a>
                </div>
              </div>
            </div>
          </div>
          
        </div>
      </div>
      
    </>
  );
};